# Generated by Django 5.2.8 on 2025-11-12 00:44

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caption', models.TextField(blank=True, null=True)),
                ('date', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='uploads/')),
                ('media_id', models.CharField(blank=True, max_length=100, null=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_id', models.CharField(max_length=100, unique=True)),
                ('text', models.TextField(blank=True, default='')),
                ('user_id', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('username', models.CharField(blank=True, default='', max_length=150)),
                ('sentiment', models.CharField(blank=True, choices=[('pos', 'Positive'), ('neu', 'Neutral'), ('neg', 'Negative')], default='', max_length=8)),
                ('sentiment_score', models.FloatField(blank=True, null=True)),
                ('interest_score', models.FloatField(blank=True, null=True)),
                ('status', models.CharField(choices=[('new', 'New'), ('review', 'Needs Review'), ('needs_reply', 'Needs Reply'), ('replied', 'Replied'), ('not_interested', 'Not Interested'), ('auto_replied', 'Auto Replied')], db_index=True, default='new', max_length=16)),
                ('last_scored_at', models.DateTimeField(blank=True, null=True)),
                ('post', models.ForeignKey(db_column='media_id', on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='dashboard.post', to_field='media_id')),
            ],
        ),
    ]
