# Generated by Django 5.2.6 on 2025-09-22 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_rename_in_reply_to_user_id_comment_user_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='status',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
