# Generated by Django 5.2.6 on 2025-09-24 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_remove_comment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='interest_score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='comment',
            name='last_scored_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='comment',
            name='sentiment',
            field=models.CharField(blank=True, choices=[('pos', 'Positive'), ('neu', 'Neutral'), ('neg', 'Negative')], default='', max_length=8),
        ),
        migrations.AddField(
            model_name='comment',
            name='sentiment_score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='comment',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('review', 'Needs Review'), ('needs_reply', 'Needs Reply'), ('replied', 'Replied'), ('not_interested', 'Not Interested'), ('auto_replied', 'Auto Replied')], db_index=True, default='new', max_length=16),
        ),
        migrations.AlterField(
            model_name='comment',
            name='comment_id',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='comment',
            name='text',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='comment',
            name='user_id',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='comment',
            name='username',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
    ]
