# Generated by Django 5.2.6 on 2025-09-24 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_comment_interest_score_comment_last_scored_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='user_id',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
    ]
