# Generated by Django 5.2.6 on 2025-09-23 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_joboffer'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgentConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='IngSW Agent', max_length=100)),
                ('is_active', models.BooleanField(default=False, help_text='Whether the agent is currently active')),
                ('description', models.TextField(blank=True, help_text='Description of what this agent does', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Agent Configuration',
                'verbose_name_plural': 'Agent Configuration',
            },
        ),
    ]
